name: Build and Push Native Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Define the full image name using your GitHub username/organization and repository name.
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build Native Docker Image
        run: ./gradlew dockerBuildNative

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker Image
        run: |
          docker tag producer:latest $IMAGE_NAME:latest
          docker tag producer:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}